### ISSUE TITLE
Improve how dialogs are created and add localization support

### ISSUE THREAD

**Issue by Ven0maus** [Ven0maus/Emberpoint#119]
**Explain your improvement in detail here:**
Dialogs are created 2 ways right now:
- DialogBuilder class
- DialogWindow.AddDialog() method

Improvements to do:
- Only use the DialogBuilder, which should be expanded to allow more complex dialogs.
- Improve the way we save and read big dialogs, (don't define them within cs files)
(Should we use some special dialog files that support localization?)
- Add localization for dialogs

**How will this improvement affect the current behaviour?**
Will be easier to create new dialogs in the future, and have an easy way to add localization for them.

**Guidelines or remarks to how this improvement should be tackled?**
- Research the best way(s) to add localization to big texts, (resx files might not be the right way?)

**Comment by RychuP** [comment]
Considering there might be different options for the dialog rather then just pressing 'Enter', perhaps it could be better to allow the DialogWindow to implement its own ProcessKeyboard?

**Comment by Ven0maus** [comment]
Yep it should definitely be removed from the Player class, however the enter button seems to be hardcoded I just saw. This should probably be mapped to some button in the KeyBindings settings.

**Comment by RychuP** [comment]
I guess the hardcoded 'Enter' could be replaced with Keybindings.Confirm, however numeric options should be hardcoded (1, 2, 3, etc, for selecting available answers), unless we want the to expand the Keybindings by Option1, Option2, Option3, etc and allow the player to change those?

**Comment by Ven0maus** [comment]
I've been thinking, maybe we should have the game pause while there are dialogs available.
Also interacting with objects should probably show a proper popup window on the game window, with options. (Instead of showing this at the bottom, it might not be very clear?)
For example, when opening a wardrobe you get a selection "Hide", "Search" etc. These actions should probably also pause the game?

And then these options would just be clickable with the mouse, kind of like buttons. So you could prevent unneeded keybindings for this, just a thought.

**Comment by RychuP** [comment]
Pausing the game for some dialogs is definitely a must, unless we want the player to walk away from an unresolved dialog half way through. On the other hand, some dialogs could allow the game to continue, like this little tutorial at the beginning. If we make all the dialogs to pause the game, those that don't only serve information will need an option to skip, so those players on the impatient side can continue.

**Comment by RychuP** [comment]
Clickable buttons are nice but some players like the fast option of responding with a keystroke. I imagine player's hands will most of the time be on the keyboard? Asking them to take the hand off the keyboard and use the mouse just so they can respond to some dialog might cause frustration after a while. I imagine we could implement both options for the dialog buttons: clickable and keys 1-9 selectable.

**Comment by Ven0maus** [comment]
Alright yeah we can use the keys 1-9 for options, we can check for these in the dialog if needed.
So they can be used in other scenarios, without having to "lock" them for just dialogs.
In cases where there are options, I suppose the game is paused anyway?

**Comment by RychuP** [comment]
That sounds sensible. Indeed, there could be quick access keyboard shortcuts to some inventory items that also use 1-9 keys. In which case yes, dialogs with options will definitely need to pause the game.
