### ISSUE TITLE
Add support for showing items on the grid

### ISSUE THREAD

**Issue by Ven0maus** [Ven0maus/Emberpoint#122]
Right now the EmberGrid can only contain cells, but it should also support items.

An approach to how this could be implemented, should be discussed here first.

**Comment by JonesJ07** [comment]
@Venom0us I am familiarizing myself with the project. The first solution that comes to mind would be for EmberCell to contain an EmberItem or a collection of EmberItems. Unfortunately, the current method of rendering the grid from the blueprint text files would not offer enough flexibility to support this. Especially if we plan to put items inside of things such as a wardrobe. Did you have any direction in mind?

**Comment by Ven0maus** [comment]
Serialization part of this issue will be implemented in #31

**Comment by Ven0maus** [comment]
Implemented
