### ISSUE TITLE
SettingsWindow.ChangeLanguage() doesn't refresh its own window correctly when entered for the second time from the main menu window

### ISSUE THREAD

**Issue by RychuP** [Ven0maus/Emberpoint#128]
**Describe the bug**
Clicking on the language button in settings window doesn't always refresh it with new language.

I tracked the issue to calling Game.Reset() every time the MainMenuWindow.Show() is called. It removes all the interfaces from UserInterfaceManager.Interfaces. Method ChangeLanguage() can no longer get its parent view to refresh it after the second entry to SettingsWindow, 

Calling Game.Reset() from MainMenuWindow.Show() might need to be thought through. What if the player wants to open the main menu during game play by pressing Escape button? It will reset everything.

**To Reproduce**
Start the game, enter settings. Click on the language button and notice it refreshes the settings window with new language. Exit settings to the main menu. Enter settings again. Language button works but it doesn't refresh the settings window.

**Expected behaviour**
Clicking on language button should refresh the window every time.

**Screenshots**

**Additional context**

**Comment by Ven0maus** [comment]
Problem solved, by only resetting game state in GameOver window, also excluded contributors & settings interface from the game reset.
