### ISSUE TITLE
Create a custom base class with the basic functionalities commonly used in most windows

### ISSUE THREAD

**Issue by RychuP** [Ven0maus/Emberpoint#132]
Interfaces with a window appearance could benefit from having a custom base class rather then inheriting directly from Console. Common functionalities could include drawing borders, displaying titles and other information on or around the borders, resizing, padding, styling, etc.

**Comment by RychuP** [comment]
Can I suggest a removal of some properties from IUserInterface:
        Point Position { get; set; }
        bool IsVisible { get; set; }
        bool IsDirty { get; set; }
        SadConsole.Console Console { get; }
Assuming all interface classes inherit from Console the first 3 are present in ScreenObject and the fourth I can't really imagine the use of.

**Comment by Ven0maus** [comment]
@RychuP Should the other consoles also use Window as base?
Eg.

- FullMoonBackgroundWindow
- GameWindow
- MapWindow
- WorldmapWindow

**Comment by RychuP** [comment]
I'd say only the interfaces that have the appearance of the window with a border, like the inventory or the dialog. I haven't had time to do the Map and the developer window yet. All the main menu interfaces don't need to inherit from the Window.

**Comment by RychuP** [comment]
I'd say only the interfaces that have the appearance of the window with a border, like the inventory or the dialog. I haven't had time to do the Map and the developer window yet. All the main menu interfaces don't need to inherit from the Window.

As a matter of fact, I think I will rename this base class to BorderedWindow to better describe what it does.

Can I suggest that instead of ConsoleWindows and ControlWindows classification you applied we could go with GameplayWindows and MenuWindows? GameplayWindows are basically all windows that can appear or can appear on the screen after the player presses Play (map, inventory, fov, dialog, etc) in the main menu and the MenuWindows are those that appear before the game starts (main menu, settings, contributors, etc) or when the player presses Escape button to change some settings in game (main menu could have a button named 'Continue' instead of 'Play' there).

MenuWindows could then have their own base class to provide similar functionality. I will probably make separate animations for Contributors and Settings window, which the base could then manage for me with minimal code from the deriving classes.

**Comment by Ven0maus** [comment]
GameplayWindows and MenuWindows sounds good to me

**Comment by RychuP** [comment]
I thought it would be good to have a base class for all the right panel windows, since they all form one column with the same width, so some of the properties (like position, size) can be calculated there.

**Comment by RychuP** [comment]
Also, I've moved the helper classes that display the main menu animation to the main menu class file to reduce the unnecessary clutter.

**Comment by Ven0maus** [comment]
I wouldn't go too much into inheritance, A generic base class that does most of the common functions should normally be sufficient for all windows. Otherwise you end up with a bunch of base classes eventually, which clutters the project up

**Comment by RychuP** [comment]
Ok, sounds sensible. I won't push that commit.
