### ISSUE TITLE
Interaction occurs in the direction the player is facing only 

### ISSUE THREAD

**Issue by RychuP** [Ven0maus/Emberpoint#135]
**Describe the bug**
I am not entirely sure whether this is intentional or not. I haven't fully investigated it. Interaction with cells doesn't get detected for nearby cells but only those that the player is facing.

**To Reproduce**
Approach a door on a western wall from either south or north. Interaction doesn't get detected unless you press the 'right' button.

**Expected behavior**
Player is able to interact with all neighbouring cells regardless of the direction they are facing. 

But then again, it might not actually be a bad thing to be able to distinguish between the cells the player wants or can (for example fight only one enemy at a time) interact with, in which case the interaction window should keep an up-to-date information of what the player is currently facing.

**Comment by RychuP** [comment]
This again, as with the flashlight battery drain, begs a question what actually is classed as a player turn? What advances game time? Is it just player movement or should the actions count as well? 

Say the player is standing between a wardrobe to the left and the door to the right. Can they open the door and interact with the wardrobe during the same turn or are these two actions two separate time events?

**Comment by RychuP** [comment]
Perhaps each action the player can take (ie movement, interaction, fighting, etc) should have a time cost (some could be a fraction of a turn, others multiple turns, etc) attached to it with the game updating time on each fully completed turn. I am sure I've seen this concept in some other rogue likes I came across...

**Comment by RychuP** [comment]
An event based Clock class comes to mind that could synchronise everything in the game. Some things could be happening around the mansion at certain times? 

"In the distance you hear a grandfather clock bell announcing midnight. Sudden chill moves across the room. You feel your arm hair stand up..."

Ideas, ideas...

**Comment by Ven0maus** [comment]
During development of this, we went with the "works as designed" approach, to prevent problems with such cases as mentioned where there are multiple interactable cells around the player position. It was the easy solution at the time. Although this "solution" could be somewhat "improved" by grabbing the right interaction when there is only one interactable cell (even if you're not facing it).

**Comment by Ven0maus** [comment]
Added some QoL to detect interactable cells in a better way
